#!/bin/bash
set -uo pipefail
source "$(dirname "$0")/lib.sh"

craft_rules_off && exit 0
require_jq

input=$(cat)
path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')
[ -n "$path" ] || exit 0

hash_full='^#([^!]|$)'
hash_trailing='[^[:space:]][[:space:]]+#([[:space:]]|$)'
slash_full='^(//|/\*)'
slash_trailing='[^[:space:]][[:space:]]+(//|/\*)'

case "$path" in
  *.py) patterns="$hash_full|$hash_trailing|^[rRuUbB]?(\"\"\"|''')" ;;
  *.rb|*.sh|*.bash|*.zsh) patterns="$hash_full|$hash_trailing" ;;
  *.php) patterns="$slash_full|$slash_trailing|^#([^![]|$)" ;;
  *.vue|*.svelte) patterns="$slash_full|$slash_trailing|<!--" ;;
  *.kt|*.kts|*.java|*.swift|*.m|*.mm|*.dart|*.ts|*.tsx|*.js|*.jsx|*.mjs|*.cjs|*.go|*.rs|*.c|*.h|*.cc|*.cpp|*.hpp|*.cs|*.scala)
    patterns="$slash_full|$slash_trailing" ;;
  *) exit 0 ;;
esac

machine_read='^#!|ignore:|ignore_for_file:|go:build|go:generate|go:embed|\+build|@ts-|eslint-|prettier-ignore|biome-ignore|type:[[:space:]]*ignore|noqa|pylint:|ruff:|fmt:|mypy:|pyright:|shellcheck[[:space:]]|@Suppress|SPDX-License|Copyright|Licensed under|Code generated|DO NOT EDIT|AUTOGENERATED|@generated|swiftlint:|ktlint|NOLINT|nolint|istanbul ignore|c8 ignore|v8 ignore|@jsx|@flow|frozen_string_literal:|-\*- coding|/// <reference'

added=$(added_lines "$(old_fragment "$input" "$path")" "$(new_fragment "$input")" \
  | grep -E -- "$patterns" \
  | grep -vE -- "$machine_read" \
  | head -5)

[ -n "$added" ] || exit 0
craft_is_allowed "$path" && exit 0

printf 'Craft rule: zero comments. This edit adds comment lines to %s:\n\n%s\n\nRemove them. If the code needs explaining, fix the naming and structure, or put it in your chat reply or the commit body.\nStill allowed: lint/type pragmas, shebangs, build tags, codegen banners, license headers. Comments already in the file are left alone.\nThe user asked for this comment in this request? Run  craft-allow %s  and retry.\n' \
  "${path##*/}" "$added" "$path" >&2
exit 2
