#!/bin/bash
set -uo pipefail

[ "${CLAUDE_CRAFT_RULES:-on}" = "off" ] && exit 0

input=$(cat)
path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')
[ -n "$path" ] && [ -f "$path" ] || exit 0

case "$path" in
  *.md|*.mdx|*.txt|*.json|*.lock|*.csv|*.svg|*/SKILL.md) exit 0 ;;
  *.kt|*.kts|*.java|*.swift|*.m|*.mm|*.dart|*.ts|*.tsx|*.js|*.jsx|*.go|*.rs|*.py|*.rb|*.sh|*.bash|*.zsh|*.c|*.h|*.cc|*.cpp|*.hpp|*.cs|*.php|*.scala|*.vue|*.svelte) ;;
  *) exit 0 ;;
esac

repo=$(git -C "$(dirname "$path")" rev-parse --show-toplevel 2>/dev/null) || exit 0
git -C "$repo" ls-files --error-unmatch "$path" >/dev/null 2>&1 || exit 0

added=$(git -C "$repo" diff -U0 -- "$path" 2>/dev/null \
  | grep '^+' | grep -v '^+++' | sed 's/^+//' \
  | sed 's/^[[:space:]]*//' \
  | grep -E '^(//|#|/\*|\*[^/]|--[[:space:]]|<!--|"""|'"'''"')' \
  | grep -vE '^#!|^//[[:space:]]*(ignore:|go:build|\+build|@ts-|eslint-|prettier-|biome-)|^#[[:space:]]*(type:[[:space:]]*ignore|noqa|pylint:|ruff:|fmt:)|@Suppress|SPDX-License|Copyright|Licensed under|^\*[[:space:]]*$|Code generated|DO NOT EDIT|AUTOGENERATED|@generated' \
  | head -5)

[ -n "$added" ] || exit 0

printf 'Craft rule: zero comments. You added comment lines to %s:\n\n%s\n\nRemove them. If the code needs explaining, fix the naming and structure, or put it in your chat reply or the commit body.\nStill allowed: lint/type pragmas, shebangs, build tags, codegen banners, license headers. Leave pre-existing comments alone.\n' \
  "$(basename "$path")" "$added" >&2
exit 2
